### ISSUE TITLE
LockScreen Theme won't show up on iOS13.3beta2 or iOS13.3beta3

### ISSUE THREAD

**Issue by Halo-Michael** [Matchstic/Xen-HTML#156]
**Describe the bug**
LockScreen Theme won't show up on iOS13.2 or higher version.

**To Reproduce**
1. Any Theme won't show up on a "Locked screen". (Will only appear on devices with a password set), and it will only happen on iOS13.2 or higher version.

**Expected behavior**
Shows Theme on "Locked screen" like iOS13.1.3 or lower version.

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS13.2

**Additional context**
The same thing happens on almost all of the "Locked Screen" tweaks. For example, SimpleLS2, ChargeAnimations, Flexing.

**Comment by Matchstic** [comment]
Fixed in v1.1~beta1 and newer, on https://xenpublic.incendo.ws

**Comment by Halo-Michael** [comment]
No it's not. I'm using 1.1~beta2 but this issue still exits.

**Comment by Halo-Michael** [comment]
So can you re-open it?

**Comment by Halo-Michael** [comment]
If you need a video to show that, here is: https://twitter.com/halo_michael/status/1198260337411145728?s=20

**Comment by Matchstic** [comment]
This sounds like the WebGL dylib isn’t running. Have you disabled it manually?

**Comment by Halo-Michael** [comment]
> This sounds like the WebGL dylib isn’t running. Have you disabled it manually?

No, I didn't disabled any dylib. If you have a device on 13.2 or higher, you should be able to reproduce it easily. (Same issue happened in SimpleLS2, ChargeAnimations, Flexing).

**Comment by Halo-Michael** [comment]
I guess it should be related to some of the new security restrictions in 13.2.

**Comment by Matchstic** [comment]
This is why I’m saying it’s fixed; I’m on 13.2, and have this working just fine with a passcode set. It required specific changes from me to work in the first place.

**Comment by Halo-Michael** [comment]
Even on a test device 6s on 13.2.3 without any other tweaks installed, this bug still exists.

**Comment by Matchstic** [comment]
Which package manager are you installing from? It could be you need to restart backboardd for the WebGL dylib to run.

**Comment by Halo-Michael** [comment]
> Which package manager are you installing from? It could be you need to restart backboardd for the WebGL dylib to run.
> […](#)
> On 25 Nov 2019, at 14:55, Halo-Michael ***@***.***> wrote: ﻿ Even on a test device 6s on 13.2.3 without any other tweaks installed, this bug still exists. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

Cydia. I restarted backboardd but still doesn't work.

**Comment by Matchstic** [comment]
In the system log, anything from the WebGL dylib stating that it’s not loading?

**Comment by Halo-Michael** [comment]
> In the system log, anything from the WebGL dylib stating that it’s not loading?
> […](#)
> On 25 Nov 2019, at 15:30, Halo-Michael ***@***.***> wrote: ﻿ Which package manager are you installing from? It could be you need to restart backboardd for the WebGL dylib to run. … On 25 Nov 2019, at 14:55, Halo-Michael @.***> wrote: ﻿ Even on a test device 6s on 13.2.3 without any other tweaks installed, this bug still exists. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Cydia. I restarted backboardd but still doesn't work. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

I can't get it, ondeviceconsole doesn't work.

**Comment by Halo-Michael** [comment]
If you don't mind my mistake, I think your confusion may be related to my modification of the title.

**Comment by Matchstic** [comment]
Yep, that’ll do it alright! In that case, I’ll come back to this when iOS 13.3 is not in beta; it doesn’t make sense to support beta iOS versions.

**Comment by Halo-Michael** [comment]
> Yep, that’ll do it alright! In that case, I’ll come back to this when iOS 13.3 is not in beta; it doesn’t make sense to support beta iOS versions.

Thanks.

**Comment by GERATKD** [comment]
> > Yep, that’ll do it alright! In that case, I’ll come back to this when iOS 13.3 is not in beta; it doesn’t make sense to support beta iOS versions.
> 
> Thanks.

did you resolve it? I'm searching the same solution toon /:

**Comment by Halo-Michael** [comment]
I think that's time :)

**Comment by Halo-Michael** [comment]
@Matchstic I think you should check this: https://twitter.com/aydenpanhuyzen/status/1205981143377612800?s=20
This bug should be fixed.

**Comment by Matchstic** [comment]
Thanks, I’ve already seen this; that’ll be the first to try.

**Comment by sohsatoh** [comment]
Add
- (BOOL)_canShowWhileLocked {
        return YES;
}
to XENDashBoardWebViewController.

I think you've already noticed that though.

**Comment by Matchstic** [comment]
I have thanks, just need the time to add the change
