### ISSUE TITLE
Widgetinfod crash

### ISSUE THREAD

**Issue by Duckyz** [Matchstic/Xen-HTML#235]
Widgetinfod has been crashing. Crash report - https://pastebin.com/wFy9t1ud

**Comment by Matchstic** [comment]
Fixed in upcoming beta 3

**Comment by piverson702** [comment]
Just updated and still getting wigetinfod error on iPhone 11 pro 13.5 but my iPhone 10 max iOS 13.5 no errors same apps same everything but the newer one gets the error ?

**Comment by khal0o0** [comment]
Same here!!
Report:
https://pastebin.com/BnU5iDCb
